spring:
  application:
    name: bit
  graphql:
    path: /graphql
    graphiql:
      path: /graphiql
      enabled: false
    schema:
      locations: classpath:graphql/**/
      file-extensions: .graphqls, .gqls
      printer:
        enabled: false
      introspection:
        enabled: true
    websocket:
      connection-init-timeout: 60s
    cors:
      max-age: 1800s

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bit

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false