name: Java Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GIT_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Check if JAR file exists
        run: |
          if [ -f ./build/libs/BitO-1.0.0.jar ]; then
            echo "JAR file exists."
          else
            echo "JAR file does not exist."
            exit 1
          fi
      - name: Copy jar file to remote
        uses: appleboy/scp-action@master
        with:
          username: ec2-user
          host: ${{ secrets.SERVER_IP }}
          key: ${{ secrets.SERVER_KEY }}
          source: "./build/libs/BitO-1.0.0.jar"
          target: "/home/ec2-user/BitO-1.0.0.jar"


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            /home/ec2-user/run_app.sh
