name: GITHUB ACTIONS NAME

on:
  workflow_dispatch:
    inputs:
      input_boolean:
        description: 'This is a boolean input'
        required: true
        default: false
        type: boolean

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input
        run: echo $