name: GITHUB ACTIONS NAME

on:
  workflow_dispatch:
    inputs:
      input_choice:
        description: 'This is a choice input'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input
        run: echo $