# .github/workflows/notify-pr-review.yml
name: Notify PR Review

on:
  pull_request_review:
    types: [ submitted ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify PR Review
        uses: naver/notify-pr-review@v1.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
